
import type { Metadata } from 'next';
import { Navbar } from '@/components/navbar/navbar';
import './globals.css';

export const metadata: Metadata = {
  title: 'Where in the world?',
  description: 'Generated by app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
